Update to a post-boxo world.
ipfs/iptb-plugins pull request #59
Opened 2023-05-16 14:12 UTC by MichaelMure

Notably, this repo is an indirect dependency of github.com/ipfs/go-ipfs-http-client, which mess things quite fast as both boxo and non-boxo packages are imported.

2023-06-05 13:56 UTC, lidel commented
@MichaelMure do you need this for any specific package? would like to know before merging it 
(we want to reduce reliance on iptb in general)

2023-06-05 13:58 UTC, MichaelMure commented
> this repo is an indirect dependency of github.com/ipfs/go-ipfs-http-client

Dunno if that's still accurate with the move into kubo.

2023-06-07 23:15 UTC, Jorropo requested changes

2023-06-07 23:15 UTC, Jorropo commented on .github/workflows/go-test.yml
> +        go: ["1.20.x"]
Why ?
```suggestion
        go: ["1.19.x", "1.20.x"]
```
We usually support the two latest golang releases.

2023-06-08 08:35 UTC, MichaelMure commented on .github/workflows/go-test.yml
> +        go: ["1.20.x"]
Likely because of that CI fail: https://github.com/ipfs/iptb-plugins/actions/runs/4992996363

2023-06-08 09:26 UTC, Jorropo commented on .github/workflows/go-test.yml
> +        go: ["1.20.x"]
Can you try downgrading multierr ?
Kubo doesn't correctly work with `1.20` yet, we don't want to drop 0.19 and be cornered.

2023-06-12 13:48 UTC, lidel commented
@MichaelMure iptb was removed when https://github.com/ipfs/go-ipfs-http-client got moved to https://github.com/ipfs/kubo/tree/master/client/rpc so we'd rather deprecate and archive this repo than spend time on maintenance like this.

But we could merge this one before that happens, as long you merge the 1.19 suggestion from Jorropo

2023-06-13 09:48 UTC, MichaelMure commented
@lidel @Jorropo I've just done the Right Thing© and opened that PR when it came in my way. I don't need it especially, so feel free to do what you want with it, including closing it.

2023-07-10 13:58 UTC, aschmahmann commented
triage: seems like there's not much of a need driving changes here at the moment as this is mostly used in kubo sharness tests which are doing alright at the moment. If anyone has a need for changes here we can reopen.

Thanks @MichaelMure for trying to help out here and let us know if this becomes an issue for you🙏

2023-07-10 13:58 UTC, closed without merging